SCREEN_WIDTH = 800
SCREEN_HEIGHT = 1080

CAR_SPAWN_CHANCE = 0.25
FAST_CAR_CHANCE = 0.03

CAR_MOVE_SPEED = 7
FAST_CAR_MOVE_SPEED = 11

CAR_MOVE_INCREMENT = 2
FAST_CAR_MOVE_INCREMENT = 6

# Do not change this plz ty
TOP_EDGE = SCREEN_HEIGHT / 2
BOTTOM_EDGE = -SCREEN_HEIGHT / 2
LEFT_EDGE = -SCREEN_WIDTH / 2
RIGHT_EDGE = SCREEN_WIDTH / 2
